=== nbarath1809-dot/spotify/spotify/src/main/webapp/xml/feedback.dtd
<!ELEMENT feedback (user*)>

<!ELEMENT user (name, email, message)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT message (#PCDATA)>

=== nbarath1809-dot/spotify/spotify/src/main/webapp/xml/feedback.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE feedback SYSTEM "feedback.dtd">

<?xml-stylesheet type="text/xsl" href="feedback.xsl"?>

<feedback> 

    <user>
        <name>Iyyappan</name>
        <email>iyyappan06012007@gmail.com</email>
        <message>ok</message>
    </user>
    <user>
        <name>sdfa</name>
        <email>iyyappan06012007@gmail.com</email>
        <message>song is good</message>
    </user>
    <user>
        <name>adhikesavan</name>
        <email>adhik7@gmail.com</email>
        <message>hello</message>
    </user>
    <user>
        <name>adhik7</name>
        <email>adhik@gmail.com</email>
        <message>hi</message>
    </user>
    <user>
        <name>wwww</name>
        <email>eniya@gmail.com</email>
        <message>dsaasdf</message>
    </user>
</feedback>
